js:
  dmDateTimePickerPlugin: 
    addOn:                          'jquery-ui-timepicker-addon'
    datePicker:                     'dmDatePickerPlugin'
    timePicker:                     'dmTimePickerPlugin'
    dateTimePicker:                 'dmDateTimePickerPlugin'

css:
  dmDateTimePickerPlugin:
    addOn:                          'jquery-ui-timepicker-addon'
    all:                            'all'